### ISSUE TITLE
[suggestion] reduce new desperado's recoil

### ISSUE THREAD

**Issue by Littleevo** [Moffein/RiskyMod#17]
the new desperado can no longer proc bands, and now it also can't hit small enemies well. reducing the recoil should make stacking hemorrhage easier on smaller / farther away targets.

**Comment by Moffein** [comment]
I'll take a look at it. It can proc bands if you hit consecutive shots against enemies below half health, and will always deal more damage than the default Lights Out due to the consecutive shot bonus as well as each consecutive shot being boosted by Slayer at a lower HP threshold. The intention is for the skill to be stronger than Lights Out at close range, while being less reliable at medium to long range.

**Comment by Littleevo** [comment]
that makes a lot of sense actually. i think the new desperado in a good spot.
