### ISSUE TITLE
New patch bugs/balance feedback

### ISSUE THREAD

**Issue by breadguy69** [Moffein/RiskyMod#28]
You are probably aware of these but the Raincoat rework and Shrine player count scaling options are broken.

Also, I've done a few more runs and I think some of the healing items are too strong, Seed and Scythe in particular. I felt pretty much unkillable with like 40 hp/s on kill from scythe by stage 5 and the 5% base lifesteal from Seed. I think Seed would be fine with just a number nerf down to like 3-4% (+2% per stack) or something, but I thought Scythe would be cool with regen on crit instead of on kill. For instance like 1-2 h/s on crit for a couple seconds, using the same stacking cap as it has for the on-kill currently. Also probably doesn't need the base 5% crit chance anymore since it gives crit on kill.

Anyway I don't think the patch broke anything else, cheers

**Comment by Moffein** [comment]
Currently working on fixing the mod for the latest update, it came at a bad time since I was in the middle of some other major changes that I haven't been able to thoroughly playtest.

- Leeching Seed is getting changed so that it only scales off of initial damage (damage used for proccing) instead of the final total damage dealt, so no more Crit/Crystal synergy since it ended up being too much.
- I'll probably leave scythe as-is for now. It's in a weird spot where it heals a lot but doesn't feel like it's healing a lot. If I were to swap it back to heal-on-crit, I'd just go with the Vanilla behavior for the sake of simplicity rather than making it conditional. The 5% crit chance is mainly there since people are used to taking Scythes+Predatory for passive crit, and I want to keep that behavior.

**Comment by breadguy69** [comment]
Also I dont think the moon pillar drop chance configs are working right. I'm trying to make them only drop lunar items and I have the overwrite chance set to 100, but I only get white items.

**Comment by Moffein** [comment]
I'll take a look at that.

**Comment by Moffein** [comment]
Forgot to mention this in the patchnotes, but the Lunar bug is fixed now. Been changed from an overwrite chance into just a normal drop chance.
