### ISSUE TITLE
Latest update breaks mod loading 

### ISSUE THREAD

**Issue by DarSitam** [Moffein/RiskyMod#56]
![image](https://github.com/Moffein/RiskyMod/assets/106157297/c0d8c77f-0681-4d7c-adb8-1dabeaf72d58)
[LogOutput.log](https://github.com/Moffein/RiskyMod/files/15009276/LogOutput.log)

Disabling RiskyMod makes the modpack load fine

**Comment by DarSitam** [comment]
Ok so, after 4 hours, the game works fine. It might have been some weird caching issues, but now it's fixed

**Comment by DarSitam** [comment]
Sorry but the issue wasn't coming from a caching error, but from StarStorm 2. Enabling it with RiskyMod causes this issue

**Comment by Moffein** [comment]
Thanks for reporting this.
I've uploaded a fix. Seems like the SS2 compatibility code in the previous update was causing MSU to hang up and throw errors before RiskyMod could load.

Seems like I'll need to scrap the fix for Gunner Turrets/Drone Refabricators for now.
Let me know if it the mod runs now.

**Comment by Moffein** [comment]
Did more looking in to it, and managed to fix the Gunner Turret compatibility thing. Version 1.5.19 should show up on Thunderstore soon.

**Comment by DarSitam** [comment]
I can confirm it works !
